import { useEffect, useMemo, useState } from 'react'
import { ArrowLeft, ArrowRight, Check, ChevronDown, Clock3, ExternalLink, FileText, GitBranch, Globe2, Image, Inbox, Link2, Menu, MessageCircle, Mic, Plus, RotateCcw, Rss, Search, Settings, Sparkles, Square, Upload, X } from 'lucide-react'
import type { AttentionBudget, AttentionSignal, EvidenceViewModel, KnowledgeItem, Source, WatchFrequency } from './domain/types'
import { archiveAction, createKnowledgeItem, groupPosterAction } from './domain/knowledge'
import { demoFacts, demoSignals, demoSources, initialGoal, initialKnowledge, knowledgeSources } from './demo/demo-data'
import { DemoAttentionAnalyzer } from './services/demo-analyzer'
import { RssSourceDrawer } from './rss/RssSourceDrawer'
import { useRss } from './rss/useRss'
import { RssItems } from './rss/RssItems'
import { rssApi } from './rss/api'
import type { RssItemDto } from './rss/types'
import type { RssSourceDto } from './rss/types'
import { RssSourcesSettings } from './rss/RssSourcesSettings'

type View = 'now' | 'knowledge' | 'settings'
const analyzer = new DemoAttentionAnalyzer()
const sourceIcons = { pdf: FileText, image: Image, url: Globe2, text: Menu }

function SignalItem({ signal, onAcknowledge, onDefer, onEvidence }: { signal: AttentionSignal; onAcknowledge: (id: string) => void; onDefer: (id: string) => void; onEvidence: (source: Source) => void }) {
  const source = demoSources.find((item) => item.name === signal.source)
  return <article className={`signal signal--${signal.kind}`} data-testid="now-signal">
    <div className="signal__rail" aria-hidden="true"><span>{signal.kind === 'new' ? '+' : '!'}</span></div>
    <div className="signal__body"><div className="signal__meta"><span className="signal__kind">{signal.kind === 'new' ? '新信息' : '行动'}</span><span>{signal.source}</span></div><h2>{signal.title}</h2><p className="signal__reason">{signal.reason}</p>
      <div className="signal__actions"><button className="text-action text-action--primary" aria-label={`知道了：${signal.title}`} onClick={() => onAcknowledge(signal.id)}><Check size={15} />知道了</button><button className="text-action" aria-label={`稍后处理：${signal.title}`} onClick={() => onDefer(signal.id)}><Clock3 size={15} />稍后</button><button className="text-action text-action--evidence" aria-label={`查看证据：${signal.title}`} onClick={() => source && onEvidence(source)}><Link2 size={14} />查看来源</button></div>
    </div></article>
}

function KnownItem({ signal, onEvidence }: { signal: AttentionSignal; onEvidence: (source: Source) => void }) {
  const [open, setOpen] = useState(false)
  const source = demoSources.find((item) => item.name === signal.source)
  const kindLabel = signal.kind === 'changed' ? '变化' : signal.kind === 'new' ? '新信息' : '行动'

  return <article className="known-item">
    <button className="known-item__toggle" aria-expanded={open} aria-controls={`known-detail-${signal.id}`} onClick={() => setOpen(!open)}>
      <span className={`known-item__dot known-item__dot--${signal.kind}`} aria-hidden="true" />
      <span className="known-item__summary"><span>{kindLabel} · {signal.source}</span><strong>{signal.title}</strong></span>
      <ChevronDown className={open ? 'is-open' : ''} size={15} aria-hidden="true" />
    </button>
    {open && <div className="known-item__detail" id={`known-detail-${signal.id}`}>
      <span>为什么重要</span><p>{signal.reason}</p>
      <span>证据摘要</span><blockquote>{signal.evidence}</blockquote>
      {source && <button className="known-item__source" aria-label={`查看已知来源：${signal.title}`} onClick={() => onEvidence(source)}><Link2 size={13} />查看来源</button>}
    </div>}
  </article>
}

function KnownBoard({ signals, reviewMode, onEvidence }: { signals: AttentionSignal[]; reviewMode: boolean; onEvidence: (source: Source) => void }) {
  return <aside className="known-board" aria-label="今天你已经知道">
    <div className="known-board__heading"><div><span className="eyebrow">{reviewMode ? 'REVIEW · TODAY I KNOW' : 'TODAY I KNOW'}</span><h2>{reviewMode ? '审阅你已经确认的内容' : '今天你已经知道'}</h2></div><span className="known-board__count" aria-label={`${signals.length} 条已知道`}>{signals.length}</span></div>
    {signals.length > 0 ? <div className="known-list">{signals.map((signal) => <KnownItem key={signal.id} signal={signal} onEvidence={onEvidence} />)}</div> : <p className="known-empty">当你点击“知道了”，信息会留在这里。知了会记住你已确认的事，不再重复占用当前注意力。</p>}
  </aside>
}

function PosterAction({ onEvidence, onSources, onComplete, onSave }: { onEvidence: (source: Source) => void; onSources: (sources: Source[]) => void; onComplete: () => void; onSave: () => void }) {
  const [open, setOpen] = useState(false)
  const action = groupPosterAction(demoFacts)
  const sourceById = new Map(demoSources.map((source) => [source.id, source]))
  return <article className="signal signal--action action-card" data-testid="now-signal"><div className="signal__rail" aria-hidden="true"><span>!</span></div><div className="signal__body">
    <div className="signal__meta"><span className="signal__kind">行动</span><span>{action.deadline}</span></div><h2>{action.title}</h2><div className="action-summary"><span>A3 · 竖版</span><span>300 DPI</span><span className="change-note">1 项要求有变化</span></div>
    <div className="signal__actions"><button className="text-action text-action--primary" aria-label="标记行动完成" onClick={onComplete}><Check size={15} />完成</button><button className="text-action" onClick={() => setOpen(!open)} aria-label="查看行动详情" aria-expanded={open}>查看详情<ChevronDown className={open ? 'is-open' : ''} size={14} /></button><button className="text-action text-action--evidence" onClick={() => onSources(['rules', 'schedule', 'team'].map((id) => sourceById.get(id)!))}><Link2 size={14} />3 个来源</button></div>
    {open && <div className="action-detail"><div className="detail-topline"><span>需要完成</span><button onClick={onSave}>保存相关知识</button></div>{demoFacts.map((fact) => { const source = sourceById.get(fact.sourceIds.at(-1)!)!; return <div className="requirement" key={fact.id}><div><span>{fact.label}</span><strong>{fact.value}</strong>{fact.revisions.length > 0 && <small>原为 {fact.revisions[0].previousValue}</small>}</div><button aria-label={`查看证据：${fact.label}`} onClick={() => onEvidence(source)}><ExternalLink size={14} />证据</button></div> })}</div>}
  </div></article>
}

function evidenceFromSource(source: Source): EvidenceViewModel {
  return { title: source.name, kind: source.kind, preview: source.target?.preview ?? source.detail, excerpt: source.target?.excerpt ?? '', locator: source.target?.locator ?? source.detail }
}

function EvidenceDrawer({ evidence, onClose }: { evidence: EvidenceViewModel; onClose: () => void }) {
  const Icon = sourceIcons[evidence.kind]
  return <div className="drawer-layer"><button className="drawer-backdrop" aria-label="关闭来源" onClick={onClose} /><aside className="drawer evidence-drawer" role="dialog" aria-modal="true" aria-label="来源"><div className="drawer__header"><div><span className="eyebrow">SOURCE</span><h2>{evidence.title}</h2></div><button className="icon-button" aria-label="关闭" onClick={onClose}><X size={20} /></button></div><div className={`evidence-preview evidence-preview--${evidence.kind}`}><Icon size={25} /><span>{evidence.preview}</span><div className="evidence-highlight">{evidence.excerpt}</div></div><div className="evidence-locator"><span>定位</span><strong>{evidence.locator}</strong></div><div className="source-viewer-actions"><button>查看完整上下文</button><button className="open-source" onClick={() => evidence.url && window.open(evidence.url, '_blank', 'noopener,noreferrer')}>打开原始来源<ExternalLink size={15} /></button></div></aside></div>
}

function SourceListDialog({ sources, onSelect, onClose }: { sources: Source[]; onSelect: (source: Source) => void; onClose: () => void }) {
  return <div className="drawer-layer source-dialog-layer"><button className="drawer-backdrop" aria-label="关闭来源列表" onClick={onClose} /><section className="source-dialog" role="dialog" aria-modal="true" aria-label="选择来源"><div className="drawer__header"><div><span className="eyebrow">SOURCES</span><h2>选择来源</h2></div><button className="icon-button" aria-label="关闭" onClick={onClose}><X size={20} /></button></div><div className="source-dialog__list">{sources.map((source) => { const Icon = sourceIcons[source.kind]; return <button key={source.id} aria-label={`${source.name} ${source.target?.locator}`} onClick={() => onSelect(source)}><Icon size={17} /><span><strong>{source.name}</strong><small>{source.target?.locator}</small></span><ArrowRight size={15} /></button> })}</div></section></div>
}

function ImportDrawer({ goal, onClose, onAnalyze, onOpenRss }: { goal: string; onClose: () => void; onAnalyze: (goal: string, sources: Source[]) => Promise<void>; onOpenRss: () => void }) {
  const [draft, setDraft] = useState(goal); const [items, setItems] = useState(demoSources); const [busy, setBusy] = useState(false)
  const run = async () => { setBusy(true); await onAnalyze(draft, items); setBusy(false) }
  return <div className="drawer-layer"><button className="drawer-backdrop" aria-label="关闭信息输入" onClick={onClose} /><aside className="drawer" role="dialog" aria-modal="true" aria-label="信息输入"><div className="drawer__header"><div><span className="eyebrow">CONTEXT</span><h2>信息输入</h2></div><button className="icon-button" aria-label="关闭" onClick={onClose}><X size={20} /></button></div><label className="goal-field"><span>当前目标</span><textarea aria-label="当前目标" value={draft} onChange={(event) => setDraft(event.target.value)} /></label><div className="source-picker"><div className="field-label"><span>信息来源</span><span>{items.filter((s) => s.selected).length} 个已选择</span></div>{items.map((source) => { const Icon = sourceIcons[source.kind]; return <button key={source.id} className={`source-row ${source.selected ? 'source-row--selected' : ''}`} onClick={() => setItems(items.map((item) => item.id === source.id ? { ...item, selected: !item.selected } : item))}><span className="source-row__icon"><Icon size={17} /></span><span className="source-row__name">{source.name}</span><span className="source-row__detail">{source.detail}</span><span className="source-row__check">{source.selected && <Check size={14} />}</span></button> })}</div><div className="add-source-row"><button><FileText size={16} />PDF</button><button><Image size={16} />截图</button><button><Globe2 size={16} />网页</button><button><Menu size={16} />文本</button><button onClick={onOpenRss}><Rss size={16} />RSS</button></div><button className="analyze-button" disabled={busy} onClick={run}>{busy ? <><Sparkles className="spin" size={17} />正在检查变化…</> : <>重新安排注意力<ArrowRight size={17} /></>}</button></aside></div>
}

function QuickCapture({ goal, onClose }: { goal: string; onClose: () => void }) {
  const [content, setContent] = useState(''); const [listening, setListening] = useState(false); const [voiceReady, setVoiceReady] = useState(false); const [audioUrl, setAudioUrl] = useState(''); const [audioName, setAudioName] = useState(''); const [result, setResult] = useState(false)
  useEffect(() => () => { if (audioUrl) URL.revokeObjectURL(audioUrl) }, [audioUrl])
  const chooseAudio = (file?: File) => { if (!file) return; if (audioUrl) URL.revokeObjectURL(audioUrl); setAudioUrl(URL.createObjectURL(file)); setAudioName(file.name); setResult(false) }
  const finishVoice = () => { setListening(false); setVoiceReady(true); setResult(false) }
  return <div className="quick-capture-layer"><button className="drawer-backdrop" aria-label="关闭快速接入" onClick={onClose} /><section className="quick-capture" role="dialog" aria-modal="true" aria-label="快速接入"><header><div><span className="eyebrow">QUICK CAPTURE</span><h2>接入一条新信息</h2></div><button className="icon-button" aria-label="关闭" onClick={onClose}><X size={19} /></button></header>{result ? <div className="capture-result"><Check size={21} /><span className="eyebrow">已接入</span><h3>归入：用户记忆与知识库</h3><p>发现 1 条不同于现有内容的信息。</p><button onClick={onClose}>完成</button></div> : <><label className="quick-goal"><span>当前目标</span><strong>{goal}</strong></label><textarea autoFocus aria-label="新信息" value={content} onChange={(event) => setContent(event.target.value)} placeholder="粘贴链接或文字…" /><div className="capture-media"><button className={listening ? 'is-listening' : ''} aria-label={listening ? '结束语音输入' : '开始语音输入'} onClick={() => listening ? finishVoice() : setListening(true)}>{listening ? <Square size={15} /> : <Mic size={17} />}<span>{listening ? '正在听…' : '语音'}</span></button><label><Upload size={16} /><span>上传音频</span><input aria-label="上传音频" type="file" accept="audio/*" onChange={(event) => chooseAudio(event.target.files?.[0])} /></label></div>{voiceReady && <p className="voice-ready"><Check size={14} />已接入一段语音</p>}{audioUrl && <div className="audio-preview"><span>{audioName}</span><audio controls src={audioUrl}>你的浏览器不支持音频播放。</audio></div>}<button className="capture-submit" disabled={!content.trim() && !voiceReady && !audioUrl} onClick={() => setResult(true)}>接入信息<ArrowRight size={16} /></button></>}</section></div>
}

function KnowledgeView({ items, selected, onSelect, onEvidence }: { items: KnowledgeItem[]; selected: KnowledgeItem | null; onSelect: (item: KnowledgeItem | null) => void; onEvidence: (source: Source) => void }) {
  const [history, setHistory] = useState(false); const [assistant, setAssistant] = useState(false)
  if (selected) { const hasHistory = ['change-detection', 'poster-knowledge'].includes(selected.id); const related = selected.relatedIds.map((id) => items.find((item) => item.id === id)).filter(Boolean) as KnowledgeItem[]; return <section className="knowledge-page"><button className="back-button" onClick={() => onSelect(null)}><ArrowLeft size={15} />知识库</button><span className="eyebrow">{selected.categories.join(' · ')}</span><h1>{selected.title}</h1><p className="knowledge-summary">{selected.summary}</p><div className="source-block"><div className="minor-heading"><span>来源</span><span>{selected.sourceIds.length}</span></div>{selected.sourceIds.map((id) => { const source = [...demoSources, ...knowledgeSources].find((item) => item.id === id)!; return <button key={id} aria-label={`${source.name} ${source.target?.locator}`} onClick={() => onEvidence(source)}><span>{source.name}</span><span>{source.target?.locator}</span><ExternalLink size={14} /></button> })}</div>{hasHistory && <><button className="history-toggle" aria-expanded={history} onClick={() => setHistory(!history)}><span>历史变化（1）</span><ChevronDown className={history ? 'is-open' : ''} size={16} /></button>{history && <div className="timeline"><div><time>现在</time><strong>明天 11:30 前</strong><span>群公告截图</span></div><div><time>此前</time><strong>明天 12:00 前</strong><span>比赛说明第 4 节</span></div></div>}</>}{related.length > 0 && <div className="relation-panel"><div className="minor-heading"><span>相关内容</span><GitBranch size={15} /></div><div className="related-topic-list">{related.map((item) => <button key={item.id} onClick={() => onSelect(item)}><span>{item.title}</span><ArrowRight size={14} /></button>)}</div></div>}</section> }
  const groups = [...new Set(items.map((item) => item.categories[0]))].map((category) => ({ category, items: items.filter((item) => item.categories[0] === category) }))
  return <section className="knowledge-page"><div className="knowledge-header"><div><span className="eyebrow">LIBRARY</span><h1>知识库</h1></div><button className="ask-button" onClick={() => setAssistant(!assistant)}><MessageCircle size={16} />问知识库</button></div>{assistant && <div className="assistant-box"><div className="assistant-input"><Search size={16} /><span>海报提交有哪些要求？</span></div><p>使用 A3 竖版画布，以 300 DPI 导出；当前提交截止为明天 11:30。</p><button onClick={() => onEvidence(demoSources[0])}>比赛说明 · 第 4 页 <ExternalLink size={13} /></button></div>}<div className="category-list">{groups.map((group) => <section className="category-group" key={group.category}><div className="category-heading"><h2>{group.category}</h2><span>{group.items.length} 个主题</span></div><div className="knowledge-list">{group.items.map((item) => <button key={item.id} onClick={() => onSelect(item)}><span className="knowledge-list__mark">{item.title.slice(0, 1)}</span><span><strong>{item.title}</strong><small>{item.summary}</small><em>{item.sourceIds.length} 个来源</em></span><ArrowRight size={16} /></button>)}</div></section>)}</div></section>
}

function SettingsView({ frequency, onFrequency, rssSources, onRssUpdate, onRssRun }: { frequency: WatchFrequency; onFrequency: (value: WatchFrequency) => void; rssSources: RssSourceDto[]; onRssUpdate: (id: string, changes: Partial<Pick<RssSourceDto, 'status' | 'frequency'>>) => Promise<unknown>; onRssRun: (id: string) => Promise<unknown> }) {
  const [meaningful, setMeaningful] = useState(true); const [itemFrequency, setItemFrequency] = useState<WatchFrequency>('adaptive')
  return <section className="settings-page"><span className="eyebrow">PREFERENCES</span><h1>设置</h1><div className="settings-group"><h2>变化关注</h2><label><span><strong>默认检查频率</strong><small>新关注内容默认使用这个频率</small></span><select aria-label="默认检查频率" value={frequency} onChange={(event) => onFrequency(event.target.value as WatchFrequency)}><option value="adaptive">自适应</option><option value="immediate">尽快</option><option value="daily">每天</option><option value="weekly">每周</option><option value="manual">仅手动</option></select></label><label><span><strong>只有发生有意义变化时提醒</strong><small>排版、广告等变化不会打扰你</small></span><button className={`switch ${meaningful ? 'on' : ''}`} aria-pressed={meaningful} onClick={() => setMeaningful(!meaningful)}><i /></button></label></div><RssSourcesSettings sources={rssSources} onUpdate={onRssUpdate} onRun={onRssRun} /><div className="settings-group"><h2>正在关注</h2><div className="watch-row"><span><strong>完成黑客松海报</strong><small>下次检查由内容状态决定</small></span><select aria-label="海报检查频率" value={itemFrequency} onChange={(event) => setItemFrequency(event.target.value as WatchFrequency)}><option value="adaptive">自适应</option><option value="immediate">尽快</option><option value="daily">每天</option><option value="weekly">每周</option><option value="manual">仅手动</option></select><button>停止关注</button></div></div><div className="settings-group"><h2>知识库</h2><div className="setting-line"><span><strong>导出与备份</strong><small>Markdown、原始附件与 JSON 元数据</small></span><ArrowRight size={16} /></div></div></section>
}

export default function App() {
  const freshSignals = () => demoSignals.filter((signal) => signal.disposition !== 'known').map((signal) => ({ ...signal })); const [view, setView] = useState<View>('now'); const [signals, setSignals] = useState<AttentionSignal[]>(freshSignals); const [goal, setGoal] = useState(initialGoal); const [budget, setBudget] = useState<AttentionBudget>('one-minute'); const [actionActive, setActionActive] = useState(true); const [knowledge, setKnowledge] = useState(initialKnowledge); const [selectedKnowledge, setSelectedKnowledge] = useState<KnowledgeItem | null>(null); const [frequency, setFrequency] = useState<WatchFrequency>('adaptive'); const [importOpen, setImportOpen] = useState(false); const [rssOpen, setRssOpen] = useState(false); const [quickOpen, setQuickOpen] = useState(false); const [evidence, setEvidence] = useState<EvidenceViewModel | null>(null); const [sourceSelection, setSourceSelection] = useState<Source[]>([]); const [notice, setNotice] = useState(''); const { sources: rssSources, items: rssItems, connect: connectRss, load: loadRss, updateSource: updateRssSource, runSource: runRssSource } = useRss(); const openEvidence = (source: Source) => setEvidence(evidenceFromSource(source))
  useEffect(() => { void loadRss() }, [loadRss])
  const openRssEvidence = async (item: RssItemDto) => { const detail = await rssApi.getItem(item.id).catch(() => null); const source = detail?.evidence[0]; setEvidence({ title: item.sourceTitle, kind: 'url', preview: item.title, excerpt: source?.excerpt ?? item.summaryText, locator: source ? `抓取于 ${new Date(source.capturedAt).toLocaleString('zh-CN')}` : 'RSS', url: source?.url ?? item.url }) }
  useEffect(() => { const openQuick = (event: KeyboardEvent) => { if ((event.ctrlKey || event.metaKey) && event.key.toLowerCase() === 'k') { event.preventDefault(); setImportOpen(false); setQuickOpen(true) } }; window.addEventListener('keydown', openQuick); return () => window.removeEventListener('keydown', openQuick) }, [])
  const visibleSignals = useMemo(() => signals.filter((signal) => signal.disposition === 'unread' && ['team-deadline', 'public-github'].includes(signal.id)), [signals])
  const knownSignals = useMemo(() => signals.filter((signal) => signal.disposition === 'known'), [signals])
  const reviewMode = visibleSignals.length === 0 && !actionActive && knownSignals.length > 0
  const flash = (text: string) => { setNotice(text); window.setTimeout(() => setNotice(''), 2200) }
  const acknowledge = (id: string) => { setSignals((current) => current.map((signal) => signal.id === id ? { ...signal, disposition: 'known' } : signal)); flash('已加入“今天你已经知道”') }; const defer = (id: string) => setSignals((current) => current.map((signal) => signal.id === id ? { ...signal, disposition: 'later' } : signal))
  const savePosterKnowledge = () => { if (!knowledge.some((item) => item.id === 'poster-knowledge')) setKnowledge([...knowledge, createKnowledgeItem('poster-knowledge', '黑客松展示海报要求', '参赛海报应采用 A3 竖版画布并以 300 DPI 导出。', demoFacts)]); flash('已保存相关知识，并关联 3 个来源') }
  const completeAction = () => { const archived = archiveAction(groupPosterAction(demoFacts), demoFacts, demoSources); setActionActive(false); flash(`${archived.sourceIds.length} 个引用来源已随事件归档`) }
  const reset = () => { setSignals(freshSignals()); setActionActive(true); setKnowledge(initialKnowledge); setView('now'); setSelectedKnowledge(null); setFrequency('adaptive'); flash('演示已重置') }
  return <div className="app-shell"><header className="topbar"><button className="brand brand-button" onClick={() => setView('now')}>知了<span>。</span></button><nav className="main-nav" aria-label="主导航"><button className={view === 'now' ? 'active' : ''} onClick={() => setView('now')}>现在</button><button className={view === 'knowledge' ? 'active' : ''} onClick={() => { setView('knowledge'); setSelectedKnowledge(null) }}>知识库</button></nav><div className="topbar__actions"><button className="quiet-button" onClick={reset}><RotateCcw size={15} />重置</button><button className="quiet-button settings-button" aria-label="设置" onClick={() => setView('settings')}><Settings size={17} /></button><button className="import-button" aria-label="导入新信息" onClick={() => { setQuickOpen(false); setImportOpen(true) }}><Inbox size={17} /><span>导入新信息</span></button></div></header><main id="top">
    {view === 'now' && <><section className="context-strip" aria-label="当前上下文"><div className="context-strip__goal"><span className="eyebrow">当前目标</span><p>{goal}</p></div><div className="budget-control"><span className="eyebrow">注意力预算</span><div className="budget-options">{([['one-minute', '1 分钟'], ['three-minutes', '3 分钟'], ['deep-dive', '深入']] as const).map(([value, label]) => <button key={value} className={budget === value ? 'active' : ''} aria-pressed={budget === value} onClick={() => setBudget(value)}>{label}</button>)}</div></div></section><section className={`attention-grid ${reviewMode ? 'attention-grid--review' : ''}`} aria-label="注意力看板"><section className="briefing"><div className="section-heading"><div><span className="eyebrow">{reviewMode ? 'INBOX READY' : `NOW · ${rssItems.length + visibleSignals.length + (actionActive ? 1 : 0)}`}</span><h1>{reviewMode ? '当前事项已处理完' : '现在值得你注意'}</h1></div><span className="updated"><span />{reviewMode ? '等待新信息' : '刚刚更新'}</span></div><div className="signal-list"><RssItems items={rssItems} onEvidence={(item) => { void openRssEvidence(item) }} />{visibleSignals.slice(0, 1).map((signal) => <SignalItem key={signal.id} signal={signal} onAcknowledge={acknowledge} onDefer={defer} onEvidence={openEvidence} />)}{actionActive && <PosterAction onEvidence={openEvidence} onSources={setSourceSelection} onComplete={completeAction} onSave={savePosterKnowledge} />}{visibleSignals.slice(1).map((signal) => <SignalItem key={signal.id} signal={signal} onAcknowledge={acknowledge} onDefer={defer} onEvidence={openEvidence} />)}</div>{!actionActive && <div className="completed-note"><Check size={17} /><span>“完成黑客松海报”已归档，相关证据已保留。</span></div>}</section><KnownBoard signals={knownSignals} reviewMode={reviewMode} onEvidence={openEvidence} /></section></>}
    {view === 'knowledge' && <KnowledgeView items={knowledge} selected={selectedKnowledge} onSelect={setSelectedKnowledge} onEvidence={openEvidence} />}{view === 'settings' && <SettingsView frequency={frequency} onFrequency={setFrequency} rssSources={rssSources} onRssUpdate={updateRssSource} onRssRun={runRssSource} />}</main>
    <button className="quick-capture-trigger" aria-label="快速接入" onClick={() => { setImportOpen(false); setQuickOpen(true) }}><Plus size={18} /><span>快速接入</span><kbd>⌘ K</kbd></button>{importOpen && <ImportDrawer goal={goal} onClose={() => setImportOpen(false)} onOpenRss={() => { setImportOpen(false); setRssOpen(true) }} onAnalyze={async (nextGoal, sources) => { await analyzer.analyze({ goal: nextGoal, budget, sources, signals }); setGoal(nextGoal); setImportOpen(false); flash('简报已按当前目标重新排列') }} />}{rssOpen && <RssSourceDrawer onClose={() => setRssOpen(false)} onConnect={connectRss} />}{quickOpen && <QuickCapture goal={goal} onClose={() => setQuickOpen(false)} />}{sourceSelection.length > 0 && <SourceListDialog sources={sourceSelection} onClose={() => setSourceSelection([])} onSelect={(source) => { setSourceSelection([]); openEvidence(source) }} />}{evidence && <EvidenceDrawer evidence={evidence} onClose={() => setEvidence(null)} />}<div className={`toast ${notice ? 'toast--visible' : ''}`} role="status">{notice}</div></div>
}
